"""papers 加 note 欄位

Revision ID: 015487b377b9
Revises: 4c68ce364f45
Create Date: 2026-09-02 12:57:46.586489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015487b377b9'
down_revision: Union[str, Sequence[str], None] = '4c68ce364f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'note')
    # ### end Alembic commands ###
